### ISSUE TITLE
plan of translate chinese 🇨🇳

### ISSUE THREAD

**Issue by chinanf-boy** [kay-is/react-from-zero#15]
### https://github.com/chinanf-boy/react-from-zero

**Comment by kay-is** [comment]
Pretty awesome :)

**Comment by chinanf-boy** [comment]
# I think I can finish tomorrow 😊

you want add a `h2|h*` to repo

## source

```
## Translations

- [![china](https://raw.githubusercontent.com/gosquared/flags/master/flags/flags/shiny/24/China.png) **中文/Chinese**](https://github.com/chinanf-boy/react-from-zero)

```

---

## Translations

- [![china](https://raw.githubusercontent.com/gosquared/flags/master/flags/flags/shiny/24/China.png) **中文/Chinese**](https://github.com/chinanf-boy/react-from-zero)

**Comment by kay-is** [comment]
Cool, but could you keep the name in English?

**Comment by chinanf-boy** [comment]
Sure

**Comment by chinanf-boy** [comment]
## OK, Finish ❤️

**Comment by kay-is** [comment]
Thank you very much for your efforts!

:)
