### ISSUE TITLE
Rename lesson files to preserve ordering?

### ISSUE THREAD

**Issue by markerikson** [kay-is/react-from-zero#2]
The first 9 lessons currently only use one digit for their numbering, so the filenames are not sorted numerically as a result:

```
0-object-elements.html
1-element-factory.html
10-example-app.html
...
16-advanced-integration.html
2-jsx.html
3-nested-elements.html
```

Might be nice to give them two-digit numbers so everything sorts cleanly:  01, 02, 03, ... 10, 11, 12

**Comment by kay-is** [comment]
Good idea, thank you :)
