### ISSUE TITLE
Misnomer: react-from-zero - not from zero

### ISSUE THREAD

**Issue by AndrewMcSwain** [kay-is/react-from-zero#21]
Correct me if i'm wrong. I very well could be, since I'm starting from zero. This tutorial seems like more of a reference for implementing the individual techniques used in creating an app with react, rather than a tutorial 'from zero'. Shouldn't there be an explicit overview of the structure? To elucidate what I mean by structure, take, for instance, this question:  where do i put these examples in a new instance of create-react-app / App.js ?

For reference ´App.js´:

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
      </div>
    );
  }
}

export default App;

```

**Comment by kay-is** [comment]
Good point.

I think if you look at the index.js instead of the App.js, things should be clearer.

Maybe I should add some infos about this to the readme.

**Comment by kay-is** [comment]
Hope the info I added helps :)
