### ISSUE TITLE
More examples of lifecycle methods

### ISSUE THREAD

**Issue by pesterhazy** [kay-is/react-from-zero#3]
It would be cool to have an example of `componentDidUpdate` or `componentWillReceiveProps`. E.g. when you make an Ajax request in `componentDidMount` and need to re-fetch the data because the props have changed (a personal pet peeve of mine).

**Comment by kay-is** [comment]
@pesterhazy Something like this?

```
var AsyncDataView = React.createClass({

  getInitialState: function() {
    return {update: null}
  },

  componentDidMount: function() {
    this.getData(this.props.update)
  },

  componentWillReceiveProps: function(nextProps) {
    this.getData(nextProps.update)
  },

  getData: function(value) {
    this.setState({loading: true})
    setTimeout(function() {
      this.setState({loading: false, update: value + ' + server data'})
    }.bind(this), 1000)
  }, 

  render: function() {
    if (this.state.loading) return <span>Loading...</span>
    return <span>{this.state.update}</span>
  }

})

var App = React.createClass({

  getInitialState: function() {
    return {update: 'init'}
  },

  updatePropsForAsync: function() {
    this.setState({update: Math.random()})
  },

  render: function() {
    return <div>
      <button onClick={this.updatePropsForAsync}>update</button>
      <AsyncDataView update={this.state.update}/>
    </div>
  },

})
```

**Comment by pesterhazy** [comment]
@kay-is, looks great, that's exactly what I had in mind.

One more nitpick: according to the documentation (http://facebook.github.io/react/blog/2016/01/08/A-implies-B-does-not-imply-B-implies-A.html) developers should check if props have actually changed, e.g.

```
if ( nextProps.update != this.props.update) {
   this.getData(nextProps.update)
}
```

The reason is that the lifecycle method might be called even if the props are unchanged.

**Comment by kay-is** [comment]
The lifecycle methods have changed in the last release, guess I should look after this too.
